import { lstat, mkdir, readFile, realpath, rename, writeFile } from 'node:fs/promises';
import { dirname, join, sep } from 'node:path';

import type { InstallFile, InstallResponse } from './protocol.ts';

/**
 * Writes a studio export into the repository, where the zip would have put it.
 *
 * An export is three files, and those three are all this writes:
 *
 *   .relay/config.json             what the CLI reads; merged, never replaced
 *   .github/workflows/<name>.yml   the Action that runs the pipeline
 *   <product>-workflow.json        the graph, importable back into the builder
 *
 * It used to accept any `.json`, `.yml` or `.md` path in the repository, which
 * let whoever held the pairing token overwrite `package.json`, the
 * repository's own CI workflows or its README. Now a path that is not one of
 * the three shapes is refused, and so is overwriting a file an export did not
 * write: a workflow file that does not start with the export's header, or a
 * `*-workflow.json` that is not an exported graph, belongs to the repository
 * and stays as it is.
 *
 * A path is checked segment by segment before it is joined. Nothing on the
 * way to a file may be a symbolic link, and neither may the file: `.relay` or
 * `.github` linked somewhere else — inside the repository or out of it —
 * would have an install write to a place the path does not name. That is
 * looked at before a single directory is made, so a refused install leaves
 * nothing behind, and the directory a file lands in is checked once more
 * after it exists.
 *
 * `.relay/config.json` is merged rather than replaced. The canvas describes
 * the pipeline, the guardrails and delivery; it says nothing about the
 * repository's tracker, its harnesses or its test command, and installing a
 * workflow must not quietly reset what `relay init` or a person wrote there.
 * Only the sections an export produces are taken from it at all, so an
 * install cannot add a harness — which is a command the engine would run.
 */

const MAX_FILES = 20;
const MAX_BYTES = 1_000_000;
const CONFIG_PATH = '.relay/config.json';
/** `.github/workflows/<name>.yml`: the name is what the studio's slug of a workflow name can be, and a little more. */
const WORKFLOW_FILE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,99}\.ya?ml$/;
/** `<product>-workflow.json` at the root: the product's slug is lower-case letters, digits and dashes. */
const GRAPH_FILE = /^[a-z0-9][a-z0-9-]{0,60}-workflow\.json$/;
/** How every exported workflow file begins (`web/src/lib/workflow/compile.ts`). */
const WORKFLOW_HEADER = /^# Generated by .{1,80} from the workflow "/;
/** The sections of `.relay/config.json` an export produces. Anything else in an incoming config is dropped. */
const EXPORTED_CONFIG_KEYS = ['version', 'agents', 'models', 'workflow', 'unattended', 'github', 'tests', 'delivery', 'notify'];

export class InstallError extends Error {}

type Kind = 'config' | 'workflow' | 'graph';

function kindOf(segments: string[]): Kind | null {
  if (segments.length === 2 && segments[0] === '.relay' && segments[1] === 'config.json') return 'config';
  if (segments.length === 3 && segments[0] === '.github' && segments[1] === 'workflows' && WORKFLOW_FILE.test(segments[2]!)) return 'workflow';
  if (segments.length === 1 && GRAPH_FILE.test(segments[0]!)) return 'graph';
  return null;
}

export function checkInstallPath(path: unknown): string[] {
  if (typeof path !== 'string' || path.length === 0 || path.length > 200) throw new InstallError('Every file needs a path under 200 characters.');
  if (path.includes('\\') || path.includes('\0') || path.startsWith('/') || /^[A-Za-z]:/.test(path)) {
    throw new InstallError(`"${path}" is not a path relative to the repository.`);
  }
  const segments = path.split('/');
  if (segments.some((segment) => segment === '' || segment === '.' || segment === '..')) {
    throw new InstallError(`"${path}" leaves the repository or names nothing.`);
  }
  if (segments[0]?.toLowerCase() === '.git') throw new InstallError(`"${path}" is inside .git, which an export never writes to.`);
  if (kindOf(segments) === null) {
    throw new InstallError(`"${path}" is not a file an export produces: ${CONFIG_PATH}, .github/workflows/<name>.yml, or <product>-workflow.json at the root.`);
  }
  return segments;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function deepMerge(base: Record<string, unknown>, over: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = { ...base };
  for (const [key, value] of Object.entries(over)) {
    const existing = out[key];
    out[key] = isRecord(existing) && isRecord(value) ? deepMerge(existing, value) : value;
  }
  return out;
}

/** The sections of an incoming config that an export produces, and nothing a studio added beside them. */
function exportedSections(incoming: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of EXPORTED_CONFIG_KEYS) if (incoming[key] !== undefined) out[key] = incoming[key];
  return out;
}

/**
 * The studio's config over the repository's. Two sections are the
 * repository's unless the workflow actually says something: a null test
 * command means "the canvas did not name one", and of the notification
 * settings the canvas only ever describes the webhook.
 */
export function mergeInstalledConfig(existing: Record<string, unknown>, incoming: Record<string, unknown>): Record<string, unknown> {
  const over: Record<string, unknown> = exportedSections(incoming);
  const tests = incoming['tests'];
  if (isRecord(tests) && (tests['command'] === null || tests['command'] === undefined)) {
    const rest = { ...tests };
    delete rest['command'];
    over['tests'] = rest;
  }
  const notify = incoming['notify'];
  if (isRecord(notify)) {
    if (typeof notify['webhook'] === 'string' && notify['webhook'].length > 0) over['notify'] = { webhook: notify['webhook'] };
    else delete over['notify'];
  }
  return deepMerge(existing, over);
}

/**
 * Refuses a path any part of which is a symbolic link, or whose directories
 * are not directories. Parts that do not exist yet are fine: they are made.
 */
async function refuseLinks(realRoot: string, path: string, segments: string[]): Promise<void> {
  let at = realRoot;
  for (const [index, segment] of segments.entries()) {
    at = join(at, segment);
    const last = index === segments.length - 1;
    let info;
    try {
      info = await lstat(at);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
      throw error;
    }
    if (info.isSymbolicLink()) {
      throw new InstallError(`"${path}" goes through a symbolic link (${segments.slice(0, index + 1).join('/')}), so it is not written: an export only writes to real directories and files in the repository.`);
    }
    if (!last && !info.isDirectory()) throw new InstallError(`"${path}" cannot be written: ${segments.slice(0, index + 1).join('/')} is not a directory.`);
    if (last && !info.isFile()) throw new InstallError(`"${path}" is not a file in this repository.`);
  }
}

async function readText(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

/** Whether a file already in the repository is one an earlier export wrote, and so one an install may replace. */
function writtenByAnExport(kind: Kind, content: string): boolean {
  if (kind === 'workflow') return WORKFLOW_HEADER.test(content);
  if (kind === 'graph') {
    try {
      const parsed: unknown = JSON.parse(content);
      return isRecord(parsed) && typeof parsed['exportedAt'] === 'string' && isRecord(parsed['workflow']);
    } catch {
      return false;
    }
  }
  return true;
}

export async function installFiles(root: string, files: unknown): Promise<InstallResponse> {
  if (!Array.isArray(files) || files.length === 0) throw new InstallError('There are no files to install.');
  if (files.length > MAX_FILES) throw new InstallError(`An export has at most ${MAX_FILES} files.`);

  // Everything is checked before anything is written: half an install is worse than none.
  const checked = files.map((file: unknown) => {
    const entry = (file ?? {}) as Partial<InstallFile>;
    const segments = checkInstallPath(entry.path);
    const kind = kindOf(segments)!;
    if (typeof entry.content !== 'string') throw new InstallError(`"${String(entry.path)}" has no content.`);
    if (Buffer.byteLength(entry.content) > MAX_BYTES) throw new InstallError(`"${String(entry.path)}" is larger than an export ever is.`);
    if (kind === 'config') {
      try {
        if (!isRecord(JSON.parse(entry.content))) throw new Error('not an object');
      } catch {
        throw new InstallError(`${CONFIG_PATH} from the studio is not a JSON object.`);
      }
    }
    // What goes in must itself look like an export, or the next install could not replace it.
    if (kind !== 'config' && !writtenByAnExport(kind, entry.content)) {
      throw new InstallError(`"${String(entry.path)}" is not ${kind === 'workflow' ? 'a workflow file the studio generated' : 'an exported workflow graph'}.`);
    }
    return { path: entry.path as string, segments, kind, content: entry.content };
  });

  const realRoot = await realpath(root);
  // Every path, before anything is made: a directory created on the far side
  // of a link is already a write somewhere the install was not asked to go.
  for (const file of checked) await refuseLinks(realRoot, file.path, file.segments);

  const planned: Array<{ path: string; target: string; before: string | null; content: string }> = [];
  for (const file of checked) {
    const target = join(realRoot, ...file.segments);
    const before = await readText(target);
    if (before !== null && !writtenByAnExport(file.kind, before)) {
      throw new InstallError(`"${file.path}" is already in the repository and was not written by an export, so it is left as it is. Rename the workflow in the studio, or move the file yourself.`);
    }
    let content = file.content;
    if (file.kind === 'config') {
      const incoming = JSON.parse(file.content) as Record<string, unknown>;
      // A first install is the same merge, over nothing: what an install
      // never takes from a studio (a notification command, a harness) it does
      // not take the first time either.
      let existing: Record<string, unknown> = {};
      if (before !== null) {
        try {
          const parsed: unknown = JSON.parse(before);
          if (isRecord(parsed)) existing = parsed;
        } catch {
          // An unreadable config is replaced: the engine would refuse it anyway.
        }
      }
      content = JSON.stringify(mergeInstalledConfig(existing, incoming), null, 2) + '\n';
    }
    planned.push({ path: file.path, target, before, content });
  }

  // Only now, with every file read and every refusal out of the way.
  const results: InstallResponse['files'] = [];
  for (const file of planned) {
    if (file.before === file.content) {
      results.push({ path: file.path, status: 'unchanged' });
      continue;
    }
    await mkdir(dirname(file.target), { recursive: true });
    // Once more, now that the directory exists: nothing swapped in a link while the files were being read.
    const parent = await realpath(dirname(file.target));
    if (parent !== realRoot && !parent.startsWith(realRoot + sep)) {
      throw new InstallError(`"${file.path}" resolves outside the repository through a symlink.`);
    }
    const temp = `${file.target}.relay-${process.pid}.tmp`;
    await writeFile(temp, file.content);
    await rename(temp, file.target);
    results.push({ path: file.path, status: file.before === null ? 'created' : 'updated' });
  }
  return { root, files: results };
}
