// GENERATED by scripts/gen-icons.mjs — do not edit. Re-run `npm run gen:icons`.
import { SiBitbucket, SiBitrise, SiBuildkite, SiCircleci, SiCypress, SiDatadog, SiDependabot, SiDiscord, SiFigma, SiFirebase, SiGithub, SiGithubactions, SiGitlab, SiGmail, SiIntercom, SiJenkins, SiJira, SiLinear, SiNetlify, SiNotion, SiSentry, SiShortcut, SiSnyk, SiVercel, SiZendesk } from 'react-icons/si';
import { Activity, Bot, Box, Bug, CalendarClock, CloudCog, FileSearch, Flag, GitFork, GitPullRequestArrow, Globe, Hash, Headset, Mail, MessageSquare, Plug, ScanSearch, ShieldCheck, ToggleRight, Users, Workflow, Zap } from 'lucide-react';

import type { ComponentType } from 'react';

export type IconComponent = ComponentType<{ size?: number | string; className?: string; color?: string; style?: React.CSSProperties }>;

export const SI_ICONS: Record<string, IconComponent> = { SiBitbucket, SiBitrise, SiBuildkite, SiCircleci, SiCypress, SiDatadog, SiDependabot, SiDiscord, SiFigma, SiFirebase, SiGithub, SiGithubactions, SiGitlab, SiGmail, SiIntercom, SiJenkins, SiJira, SiLinear, SiNetlify, SiNotion, SiSentry, SiShortcut, SiSnyk, SiVercel, SiZendesk };

export const LUCIDE_ICONS: Record<string, IconComponent> = { Activity, Bot, Box, Bug, CalendarClock, CloudCog, FileSearch, Flag, GitFork, GitPullRequestArrow, Globe, Hash, Headset, Mail, MessageSquare, Plug, ScanSearch, ShieldCheck, ToggleRight, Users, Workflow, Zap };
