/**
 * Apps that used to be in the catalog and were taken out because no coding-agent
 * workflow needed them: social networks, CRMs, payment providers, personal to-do
 * apps, hosting consoles and the like. A saved workflow can still name one, so
 * the builder uses this to say what the step was and what to use instead,
 * rather than showing an id.
 */
export const RETIRED_CONNECTORS: Record<string, string> = {
  gitea: 'Gitea',
  radicle: 'Radicle',
  asana: 'Asana',
  clickup: 'ClickUp',
  monday: 'Monday',
  trello: 'Trello',
  height: 'Height',
  youtrack: 'YouTrack',
  basecamp: 'Basecamp',
  plane: 'Plane',
  codemagic: 'Codemagic',
  fastlane: 'Fastlane',
  'travis-ci': 'Travis CI',
  'argo-cd': 'Argo CD',
  xcode: 'Xcode',
  testflight: 'TestFlight',
  'app-store-connect': 'App Store Connect',
  'swift-package-index': 'Swift Package Index',
  'apple-developer': 'Apple Developer',
  'android-studio': 'Android Studio / Gradle',
  'google-play-console': 'Google Play Console',
  'firebase-app-distribution': 'Firebase App Distribution',
  adb: 'ADB',
  cloudflare: 'Cloudflare',
  aws: 'AWS',
  'google-cloud': 'Google Cloud',
  azure: 'Azure',
  'fly-io': 'Fly.io',
  railway: 'Railway',
  render: 'Render',
  heroku: 'Heroku',
  digitalocean: 'DigitalOcean',
  supabase: 'Supabase',
  coolify: 'Coolify',
  postgresql: 'PostgreSQL',
  mysql: 'MySQL',
  mongodb: 'MongoDB',
  redis: 'Redis',
  neon: 'Neon',
  planetscale: 'PlanetScale',
  turso: 'Turso',
  snowflake: 'Snowflake',
  bigquery: 'BigQuery',
  airtable: 'Airtable',
  npm: 'npm',
  pypi: 'PyPI',
  'crates-io': 'crates.io',
  'docker-hub': 'Docker Hub',
  ghcr: 'GitHub Container Registry',
  homebrew: 'Homebrew',
  'maven-central': 'Maven Central',
  nuget: 'NuGet',
  socket: 'Socket',
  gitguardian: 'GitGuardian',
  trivy: 'Trivy',
  sonarqube: 'SonarQube',
  playwright: 'Playwright',
  browserstack: 'BrowserStack',
  percy: 'Percy',
  chromatic: 'Chromatic',
  codecov: 'Codecov',
  storybook: 'Storybook',
  cursor: 'Cursor',
  'vs-code': 'VS Code',
  'github-copilot': 'GitHub Copilot',
  jetbrains: 'JetBrains IDEs',
  postman: 'Postman',
  raycast: 'Raycast',
  warp: 'Warp',
  gitpod: 'Gitpod / Codespaces',
  'claude-code': 'Claude Code',
  'codex-cli': 'Codex CLI',
  'gemini-cli': 'Gemini CLI',
  aider: 'Aider',
  ollama: 'Ollama',
  'openai-api': 'OpenAI API',
  'anthropic-api': 'Anthropic API',
  'hugging-face': 'Hugging Face',
  'amazon-s3': 'Amazon S3',
  'cloudflare-r2': 'Cloudflare R2',
  'google-cloud-storage': 'Google Cloud Storage',
  'backblaze-b2': 'Backblaze B2',
  auth0: 'Auth0',
  clerk: 'Clerk',
  workos: 'WorkOS',
  okta: 'Okta',
  terminal: 'Terminal command',
  'docker-desktop': 'Docker Desktop',
  'homebrew-local': 'Homebrew (local)',
  'ios-simulator': 'iOS Simulator',
  'file-watcher': 'Local file watcher',
  'google-chat': 'Google Chat',
  telegram: 'Telegram',
  whatsapp: 'WhatsApp',
  mattermost: 'Mattermost',
  zulip: 'Zulip',
  twist: 'Twist',
  resend: 'Resend',
  sendgrid: 'SendGrid',
  postmark: 'Postmark',
  mailgun: 'Mailgun',
  'amazon-ses': 'Amazon SES',
  loops: 'Loops',
  'google-calendar': 'Google Calendar',
  'outlook-calendar': 'Outlook Calendar',
  'cal-com': 'Cal.com',
  calendly: 'Calendly',
  confluence: 'Confluence',
  'google-docs': 'Google Docs',
  'google-drive': 'Google Drive',
  dropbox: 'Dropbox',
  box: 'Box',
  onedrive: 'OneDrive',
  coda: 'Coda',
  obsidian: 'Obsidian',
  sketch: 'Sketch',
  framer: 'Framer',
  canva: 'Canva',
  zeplin: 'Zeplin',
  'new-relic': 'New Relic',
  grafana: 'Grafana',
  pagerduty: 'PagerDuty',
  opsgenie: 'Opsgenie',
  honeycomb: 'Honeycomb',
  'better-stack': 'Better Stack',
  axiom: 'Axiom',
  checkly: 'Checkly',
  posthog: 'PostHog',
  mixpanel: 'Mixpanel',
  amplitude: 'Amplitude',
  segment: 'Segment',
  'google-analytics': 'Google Analytics',
  plausible: 'Plausible',
  hotjar: 'Hotjar',
  unleash: 'Unleash',
  flagsmith: 'Flagsmith',
  growthbook: 'GrowthBook',
  front: 'Front',
  'help-scout': 'Help Scout',
  crisp: 'Crisp',
  hubspot: 'HubSpot',
  salesforce: 'Salesforce',
  pipedrive: 'Pipedrive',
  attio: 'Attio',
  apollo: 'Apollo',
  stripe: 'Stripe',
  paddle: 'Paddle',
  'lemon-squeezy': 'Lemon Squeezy',
  shopify: 'Shopify',
  chargebee: 'Chargebee',
  revenuecat: 'RevenueCat',
  x: 'X (Twitter)',
  linkedin: 'LinkedIn',
  reddit: 'Reddit',
  bluesky: 'Bluesky',
  mastodon: 'Mastodon',
  threads: 'Threads',
  'product-hunt': 'Product Hunt',
  'hacker-news': 'Hacker News',
  'dev-to': 'Dev.to',
  youtube: 'YouTube',
  loom: 'Loom',
  vimeo: 'Vimeo',
  twitch: 'Twitch',
  tiktok: 'TikTok',
  instagram: 'Instagram',
  mux: 'Mux',
  todoist: 'Todoist',
  things: 'Things',
  'apple-reminders': 'Apple Reminders',
  'apple-notes': 'Apple Notes',
  'google-tasks': 'Google Tasks',
  sunsama: 'Sunsama',
  akiflow: 'Akiflow',
  zoom: 'Zoom',
  'google-meet': 'Google Meet',
  fireflies: 'Fireflies',
  tldv: 'tl;dv',
  granola: 'Granola',
  typeform: 'Typeform',
  tally: 'Tally',
  'google-forms': 'Google Forms',
  jotform: 'Jotform',
  canny: 'Canny',
  featurebase: 'Featurebase',
  productboard: 'Productboard',
  uservoice: 'UserVoice',
  wordpress: 'WordPress',
  ghost: 'Ghost',
  webflow: 'Webflow',
  contentful: 'Contentful',
  sanity: 'Sanity',
  strapi: 'Strapi',
  payload: 'Payload',
};
