// Generates src/lib/connectors/icons.generated.ts from the icon names used in the
// catalog, so the bundle carries only the brand marks it needs rather than all
// three thousand Simple Icons. Run automatically before `dev` and `build`.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const catalogDir = join(root, 'src', 'lib', 'connectors', 'catalog');
const outFile = join(root, 'src', 'lib', 'connectors', 'icons.generated.ts');

let si;
let lucide;
try {
  si = require('react-icons/si');
  lucide = require('lucide-react');
} catch (error) {
  console.error('gen-icons: run `npm install` first —', error.message);
  process.exit(1);
}

const siNames = new Set();
const lucideNames = new Set();
const missing = [];

let files = [];
try {
  files = readdirSync(catalogDir).filter((name) => name.endsWith('.ts'));
} catch {
  files = [];
}

for (const file of files) {
  const source = readFileSync(join(catalogDir, file), 'utf8');
  for (const match of source.matchAll(/\bsi:\s*['"]([A-Za-z0-9]+)['"]/g)) {
    if (typeof si[match[1]] === 'function' || typeof si[match[1]] === 'object') siNames.add(match[1]);
    else missing.push(`${file}: react-icons/si has no ${match[1]}`);
  }
  for (const match of source.matchAll(/\blucide:\s*['"]([A-Za-z0-9]+)['"]/g)) {
    if (lucide[match[1]] !== undefined) lucideNames.add(match[1]);
    else missing.push(`${file}: lucide-react has no ${match[1]}`);
  }
}

// Icons the UI itself uses as fallbacks, always included.
for (const name of ['Plug', 'Box', 'Bot', 'Zap']) if (lucide[name] !== undefined) lucideNames.add(name);

const siList = [...siNames].sort();
const lucideList = [...lucideNames].sort();

const banner = '// GENERATED by scripts/gen-icons.mjs — do not edit. Re-run `npm run gen:icons`.\n';
const siImport = siList.length > 0 ? `import { ${siList.join(', ')} } from 'react-icons/si';\n` : '';
const lucideImport = lucideList.length > 0 ? `import { ${lucideList.join(', ')} } from 'lucide-react';\n` : '';
const body =
  `import type { ComponentType } from 'react';\n\n` +
  `export type IconComponent = ComponentType<{ size?: number | string; className?: string; color?: string; style?: React.CSSProperties }>;\n\n` +
  `export const SI_ICONS: Record<string, IconComponent> = { ${siList.join(', ')} };\n\n` +
  `export const LUCIDE_ICONS: Record<string, IconComponent> = { ${lucideList.join(', ')} };\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + siImport + lucideImport + '\n' + body);

console.log(`gen-icons: ${siList.length} brand icons, ${lucideList.length} lucide icons from ${files.length} catalog file(s).`);
if (missing.length > 0) {
  console.warn(`gen-icons: ${missing.length} icon name(s) did not resolve and will fall back to a monogram:`);
  for (const line of missing) console.warn('  - ' + line);
}
