// Core nodes: the pipeline itself, gates, delivery, and generic glue that belongs to no vendor.
import { defineConnector, FIELDS, PORTS, type Connector } from '../types';

export const AGENT_OPTIONS = [
  { value: 'claude', label: 'Claude Code', description: 'Anthropic’s CLI. Reads a codebase well; the default planner and code reviewer.' },
  { value: 'codex', label: 'Codex CLI', description: 'OpenAI’s CLI. Implements inside its own sandbox; the default implementer and plan reviewer.' },
  { value: 'gemini', label: 'Gemini CLI', description: 'Google’s CLI, added as a config harness.' },
  { value: 'aider', label: 'Aider', description: 'Open-source pair programmer, added as a config harness. Implementation only.' },
];

export const REVIEW_LEVEL_OPTIONS = [
  { value: 'light', label: 'Light', description: 'Inline plan, one code-review round. Fastest.' },
  { value: 'standard', label: 'Standard', description: 'Plan review and code review, two rounds each.' },
  { value: 'thorough', label: 'Thorough', description: 'Three rounds each, every finding routed back.' },
];

export const DELIVERY_OPTIONS = [
  { value: 'none', label: 'Nothing', description: 'Leave the diff in the worktree.' },
  { value: 'branch', label: 'Commit to a branch', description: 'Local branch only, nothing pushed.' },
  { value: 'push', label: 'Push the branch', description: 'Push, but open no pull request.' },
  { value: 'pr', label: 'Open a pull request', description: 'Push and open a PR for a human to review.' },
  { value: 'merge', label: 'Merge', description: 'Merge when checks pass. Never allowed unattended.' },
];

export const MERGE_METHOD_OPTIONS = [
  { value: 'squash', label: 'Squash' },
  { value: 'merge', label: 'Merge commit' },
  { value: 'rebase', label: 'Rebase' },
];

export const CORE_CONNECTORS: Connector[] = [
  defineConnector({
    id: 'pipeline',
    name: 'Agent pipeline',
    category: 'core',
    description: 'Plan → plan review → implement → code review → tests, inside an isolated git worktree.',
    auth: 'none',
    icon: { lucide: 'Workflow', color: '#7c3aed' },
    tags: ['agents', 'plan', 'review', 'implement'],
    popular: true,
    triggers: [],
    actions: [
      {
        id: 'run',
        name: 'Run the pipeline',
        description: 'Takes a ticket, produces a reviewed, tested diff on its own branch.',
        inputs: PORTS.issueIn,
        outputs: PORTS.runOut,
        fields: [
          FIELDS.select('review', 'Review level', REVIEW_LEVEL_OPTIONS, 'standard'),
          FIELDS.select('planner', 'Planner', AGENT_OPTIONS, 'claude'),
          FIELDS.select('planReviewer', 'Plan reviewer', AGENT_OPTIONS, 'codex'),
          FIELDS.select('implementer', 'Implementer', AGENT_OPTIONS, 'codex'),
          FIELDS.select('codeReviewer', 'Code reviewer', AGENT_OPTIONS, 'claude'),
          FIELDS.number('maxPlanReviewRounds', 'Max plan review rounds', 2, 1, 3, 1),
          FIELDS.number('maxCodeReviewRounds', 'Max code review rounds', 2, 1, 3, 1),
          FIELDS.bool('runTests', 'Run the project’s test suite', true),
          FIELDS.bool('concurrentTests', 'Run tests during code review', true, 'Both look at the same tree; neither needs the other’s verdict.'),
          FIELDS.bool('primeReviewers', 'Reviewers read ahead', true, 'Reviewers open the files while the author works, so the review turn is judgement, not reading.'),
          FIELDS.text('baseBranch', 'Base branch', 'main'),
          FIELDS.text('branchPrefix', 'Branch prefix', 'relay'),
          { key: 'testCommand', label: 'Test command override', type: 'text', placeholder: 'npm test (blank = auto-detect)' },
          { key: 'maxCostUsd', label: 'Stop this run above (USD)', type: 'number', placeholder: 'unset', min: 0, step: 0.5, help: 'Checked at every phase boundary. Work so far stays on the branch.' },
        ],
      },
      {
        id: 'fast',
        name: 'Fast run (no reviews)',
        description: 'One agent plans and implements in a single session. Only the test suite checks the work.',
        inputs: PORTS.issueIn,
        outputs: PORTS.runOut,
        fields: [
          FIELDS.select('implementer', 'Agent', AGENT_OPTIONS, 'codex'),
          FIELDS.bool('runTests', 'Run the project’s test suite', true),
          { key: 'maxCostUsd', label: 'Stop this run above (USD)', type: 'number', placeholder: 'unset', min: 0, step: 0.5 },
        ],
      },
      {
        id: 'estimate',
        name: 'Estimate cost',
        description: 'Prices the run before any agent turn, from the issue and the repository size.',
        inputs: PORTS.issueIn,
        outputs: PORTS.issueOut,
        fields: [],
      },
    ],
  }),
  defineConnector({
    id: 'gates',
    name: 'Guardrails',
    category: 'core',
    description: 'Budgets, allowlists and human approval. Every gate refuses by default.',
    auth: 'none',
    icon: { lucide: 'ShieldCheck', color: '#0f766e' },
    tags: ['budget', 'allowlist', 'approval', 'kill switch'],
    popular: true,
    triggers: [],
    actions: [
      {
        id: 'budget',
        name: 'Budget gate',
        description: 'Refuses to start when the daily or per-run ceiling is reached. Never queues for tomorrow.',
        inputs: PORTS.anyIn,
        outputs: [
          { id: 'pass', label: 'Within budget', type: 'any' },
          { id: 'refused', label: 'Refused', type: 'event' },
        ],
        fields: [
          FIELDS.number('maxRunCostUsd', 'Max cost per run (USD)', 5, 0, 500, 0.5),
          FIELDS.number('maxDailyCostUsd', 'Max cost per day (USD)', 25, 0, 5000, 1),
          FIELDS.number('confirmAboveUsd', 'Ask before starting above (USD)', 10, 0, 500, 0.5),
        ],
      },
      {
        id: 'allowlist',
        name: 'Author allowlist',
        description: 'Only these people or teams may start a run. Empty means nobody may.',
        inputs: PORTS.anyIn,
        outputs: [
          { id: 'pass', label: 'Allowed', type: 'any' },
          { id: 'refused', label: 'Refused', type: 'event' },
        ],
        fields: [
          { key: 'authors', label: 'Allowed logins', type: 'textarea', placeholder: 'one per line', required: true },
          { key: 'teams', label: 'Allowed teams (org/team)', type: 'textarea', placeholder: 'acme/platform' },
        ],
      },
      {
        id: 'approval',
        name: 'Human approval',
        description: 'Pauses until a person approves in chat, on the issue, or in the dashboard.',
        inputs: PORTS.anyIn,
        outputs: [
          { id: 'approved', label: 'Approved', type: 'any' },
          { id: 'rejected', label: 'Rejected', type: 'event' },
        ],
        fields: [
          FIELDS.select('via', 'Ask via', [
            { value: 'dashboard', label: 'Dashboard' },
            { value: 'issue', label: 'Comment on the issue' },
            { value: 'chat', label: 'Chat message with buttons' },
          ]),
          { key: 'approvers', label: 'Who may approve', type: 'textarea', placeholder: 'logins, one per line' },
          FIELDS.number('timeoutHours', 'Give up after (hours)', 24, 1, 168, 1),
        ],
      },
      {
        id: 'concurrency',
        name: 'Concurrency limit',
        description: 'At most this many runs at once per repository. Extra triggers wait.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [FIELDS.number('maxConcurrentRuns', 'Max concurrent runs', 1, 1, 10, 1)],
      },
      {
        id: 'kill-switch',
        name: 'Kill switch',
        description: 'A flag re-read before every start. Flip it and nothing new begins.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [FIELDS.bool('enabled', 'Unattended runs enabled', false)],
      },
    ],
  }),
  defineConnector({
    id: 'delivery',
    name: 'Delivery',
    category: 'core',
    description: 'How far a finished run carries its own work: commit, push, pull request, merge.',
    auth: 'none',
    icon: { lucide: 'GitPullRequestArrow', color: '#2563eb' },
    tags: ['branch', 'push', 'pull request', 'merge'],
    popular: true,
    triggers: [],
    actions: [
      {
        id: 'deliver',
        name: 'Deliver the change',
        description: 'Commits, pushes, opens a PR and optionally merges, as far as the policy allows.',
        inputs: PORTS.runIn,
        outputs: PORTS.changeOut,
        fields: [
          FIELDS.select('policy', 'Deliver as far as', DELIVERY_OPTIONS, 'pr'),
          FIELDS.select('mergeMethod', 'Merge method', MERGE_METHOD_OPTIONS, 'squash'),
          FIELDS.bool('draft', 'Open as draft', true),
          FIELDS.template('prTitle', 'PR title', '{{issue.key}}: {{issue.title}}'),
          FIELDS.template('prBody', 'PR body', 'Closes {{issue.url}}\n\n{{run.summary}}\n\nReviewed by {{run.codeReviewer}}. Tests: {{run.tests}}. Cost: {{run.cost}}.'),
          { key: 'reviewers', label: 'Request reviewers', type: 'text', placeholder: 'logins, comma separated' },
          { key: 'labels', label: 'Labels', type: 'text', placeholder: 'agent, needs-review' },
          FIELDS.bool('deleteBranchOnMerge', 'Delete branch on merge', true),
          FIELDS.bool('secretScan', 'Scan for secrets before pushing', true, 'A credential-shaped change stops at the branch.'),
        ],
      },
      {
        id: 'comment-summary',
        name: 'Comment the summary on the issue',
        description: 'Posts phases, cost, tests and the PR link back where the work was asked for.',
        inputs: PORTS.runIn,
        outputs: PORTS.eventOut,
        fields: [FIELDS.template('body', 'Comment', '{{run.summary}}')],
      },
    ],
  }),
  defineConnector({
    id: 'schedule',
    name: 'Schedule',
    category: 'core',
    description: 'Start on a timer instead of an event.',
    auth: 'none',
    icon: { lucide: 'CalendarClock', color: '#ea580c' },
    tags: ['cron', 'timer', 'interval'],
    triggers: [
      {
        id: 'cron',
        name: 'On a schedule',
        description: 'Cron expression, evaluated in the workspace time zone.',
        fields: [FIELDS.text('cron', 'Cron', '0 9 * * 1-5', true), FIELDS.text('timezone', 'Time zone', 'UTC')],
        sample: { firedAt: '2026-09-23T09:00:00Z' },
      },
      {
        id: 'interval',
        name: 'Every N minutes',
        description: 'A fixed interval. Useful for polling a tracker that has no webhooks.',
        fields: [FIELDS.number('minutes', 'Minutes', 15, 1, 1440, 1)],
      },
    ],
    actions: [
      {
        id: 'delay',
        name: 'Wait',
        description: 'Pause the workflow for a fixed duration.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [FIELDS.number('minutes', 'Minutes', 10, 1, 10080, 1)],
      },
      {
        id: 'business-hours',
        name: 'Wait for business hours',
        description: 'Hold until the next window, so nobody gets paged by a bot at 3am.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [FIELDS.text('window', 'Window', '09:00-18:00 Mon-Fri'), FIELDS.text('timezone', 'Time zone', 'Europe/London')],
      },
    ],
  }),
  defineConnector({
    id: 'http',
    name: 'HTTP & webhooks',
    category: 'core',
    description: 'Any app with a URL. Receive a webhook, or call one.',
    auth: 'none',
    icon: { lucide: 'Globe', color: '#475569' },
    tags: ['webhook', 'rest', 'api', 'custom'],
    popular: true,
    triggers: [
      {
        id: 'webhook',
        name: 'Incoming webhook',
        description: 'A unique URL. POST anything to it to start the workflow.',
        fields: [FIELDS.text('secret', 'Signing secret', 'optional'), FIELDS.text('path', 'Path suffix', 'ticket-in')],
        sample: { method: 'POST', body: { title: 'Anything you send' } },
      },
    ],
    actions: [
      {
        id: 'request',
        name: 'HTTP request',
        description: 'Call any URL with a templated body.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [
          FIELDS.select('method', 'Method', [
            { value: 'POST', label: 'POST' },
            { value: 'GET', label: 'GET' },
            { value: 'PUT', label: 'PUT' },
            { value: 'PATCH', label: 'PATCH' },
            { value: 'DELETE', label: 'DELETE' },
          ]),
          FIELDS.text('url', 'URL', 'https://', true),
          { key: 'headers', label: 'Headers (JSON)', type: 'json', placeholder: '{ "authorization": "Bearer …" }' },
          FIELDS.template('body', 'Body', '{"run": "{{run.id}}", "pr": "{{run.prUrl}}"}'),
        ],
      },
      {
        id: 'post-run-json',
        name: 'Post the run as JSON',
        description: 'Sends the full run document — phases, cost, tests, delivery — to a URL.',
        inputs: PORTS.runIn,
        outputs: PORTS.eventOut,
        fields: [FIELDS.text('url', 'URL', 'https://', true)],
      },
    ],
  }),
  defineConnector({
    id: 'logic',
    name: 'Logic',
    category: 'core',
    description: 'Branch, filter, transform.',
    auth: 'none',
    icon: { lucide: 'GitFork', color: '#64748b' },
    tags: ['condition', 'filter', 'branch', 'code'],
    popular: true,
    triggers: [
      {
        id: 'manual',
        name: 'Manual start',
        description: 'A button in the dashboard, or a CLI prompt.',
        outputs: PORTS.issueOut,
        fields: [FIELDS.template('prompt', 'Default prompt', 'Fix the flaky timeout in the retry test')],
        sample: { id: 'manual', title: 'Fix the flaky timeout in the retry test', url: '' },
      },
    ],
    actions: [
      {
        id: 'condition',
        name: 'Condition',
        description: 'Route on a field: label, priority, cost, test result…',
        inputs: PORTS.anyIn,
        outputs: [
          { id: 'true', label: 'True', type: 'any' },
          { id: 'false', label: 'False', type: 'any' },
        ],
        fields: [
          FIELDS.text('left', 'Field', '{{issue.labels}}', true),
          FIELDS.select('op', 'Operator', [
            { value: 'contains', label: 'contains' },
            { value: 'equals', label: 'equals' },
            { value: 'not-equals', label: 'does not equal' },
            { value: 'gt', label: 'greater than' },
            { value: 'lt', label: 'less than' },
            { value: 'matches', label: 'matches regex' },
          ]),
          FIELDS.text('right', 'Value', 'bug', true),
        ],
      },
      {
        id: 'filter',
        name: 'Filter',
        description: 'Continue only when the expression is true; otherwise stop quietly.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [FIELDS.text('expression', 'Expression', 'issue.estimate <= 3', true)],
      },
      {
        id: 'transform',
        name: 'Transform',
        description: 'Reshape the payload with a small JavaScript function.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [{ key: 'code', label: 'Function body', type: 'textarea', default: 'return { ...input, title: input.title.trim() };' }],
      },
      {
        id: 'ai-step',
        name: 'AI step',
        description: 'One model turn with a prompt: triage, summarise, classify, draft.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [
          FIELDS.select('model', 'Model', [
            { value: 'claude-sonnet-5', label: 'Claude Sonnet 5' },
            { value: 'claude-fable-5-1', label: 'Claude Fable 5.1' },
            { value: 'claude-haiku-4-5', label: 'Claude Haiku 4.5' },
            { value: 'gpt-5', label: 'GPT-5' },
            { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
          ]),
          FIELDS.template('prompt', 'Prompt', 'Classify this ticket as bug, feature or chore and estimate size (S/M/L):\n\n{{issue.title}}\n{{issue.body}}'),
        ],
      },
      {
        id: 'merge-paths',
        name: 'Merge paths',
        description: 'Wait for every incoming branch before continuing.',
        inputs: PORTS.anyIn,
        outputs: PORTS.eventOut,
        fields: [],
      },
      {
        id: 'note',
        name: 'Note',
        description: 'A sticky note on the canvas. Does nothing at run time.',
        inputs: [],
        outputs: [],
        fields: [{ key: 'text', label: 'Text', type: 'textarea', default: 'Explain this part of the flow for your future self.' }],
      },
    ],
  }),
];
